// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB491lUDR8KizlvxtoRCcLBCsNPV2r32X0',
//     appId: '1:586180801814:web:0444f5d737433d78d54c37',
//     messagingSenderId: '586180801814',
//     projectId: 'neuflo-neuflolearn',
//     authDomain: 'neuflo-neuflolearn.firebaseapp.com',
//     storageBucket: 'neuflo-neuflolearn.firebasestorage.app',
//     measurementId: 'G-E2PVSPS7WH',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAZYaqd06xu01sRsK4q-E9ky4iomhRbrqY',
//     appId: '1:586180801814:android:26ec82706d22d030d54c37',
//     messagingSenderId: '586180801814',
//     projectId: 'neuflo-neuflolearn',
//     storageBucket: 'neuflo-neuflolearn.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAdZYoJYhtlAL0PpRdYRHlehik5iiJ36HM',
//     appId: '1:586180801814:ios:7451aa0adec4281ed54c37',
//     messagingSenderId: '586180801814',
//     projectId: 'neuflo-neuflolearn',
//     storageBucket: 'neuflo-neuflolearn.firebasestorage.app',
//     androidClientId: '586180801814-bhga5gv0u2v06nf76ukjej7c6ipujsd9.apps.googleusercontent.com',
//     iosClientId: '586180801814-1mum2bjidl7votav8dlnnm158061l137.apps.googleusercontent.com',
//     iosBundleId: 'com.neuflo.neuflolearnv1',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAdZYoJYhtlAL0PpRdYRHlehik5iiJ36HM',
//     appId: '1:586180801814:ios:7451aa0adec4281ed54c37',
//     messagingSenderId: '586180801814',
//     projectId: 'neuflo-neuflolearn',
//     storageBucket: 'neuflo-neuflolearn.firebasestorage.app',
//     androidClientId: '586180801814-bhga5gv0u2v06nf76ukjej7c6ipujsd9.apps.googleusercontent.com',
//     iosClientId: '586180801814-1mum2bjidl7votav8dlnnm158061l137.apps.googleusercontent.com',
//     iosBundleId: 'com.neuflo.neuflolearnv1',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyB491lUDR8KizlvxtoRCcLBCsNPV2r32X0',
//     appId: '1:586180801814:web:728572eb8f96d3a4d54c37',
//     messagingSenderId: '586180801814',
//     projectId: 'neuflo-neuflolearn',
//     authDomain: 'neuflo-neuflolearn.firebaseapp.com',
//     storageBucket: 'neuflo-neuflolearn.firebasestorage.app',
//     measurementId: 'G-GC7BMSKZFT',
//   );

// }
